### PR TITLE
Add option to change the separator

### PR DESCRIPTION
**Pull request by marcosgugs**

### CODE REVIEW

**Comment by trantrunghieu0809** [comment]
I think the separator default should be ','

**Comment by marcosgugs** [comment]
No problems.

In my case, with ',' as separator, when open in excel all csv columns was on the first excel column.
Other case is when have ',' in the middle of text in any column.

An exemple:

```
00000108,PACOTE ORTOPEDICO MEMBRO SUPERIOR ANTEBRACO PALMAR - UNIMED LONDRINA,7.52
00001082,PACOTE DE ATO DE COLETA, PUNÇÃO, BIÓPSIA- UNIMED LONDRINA,8.5999
```

PS: Sorry for my bad english!

**Comment by dtagdev1** [comment]
please change separator default then i will merge it

**Comment by trantrunghieu0809** [comment]
thanks @marcosgugs ,
I think separator default may be ';'
I will merge commit your

**Pull request merged**
